name: OpenWrt 官方主线｜SSH手动配置编译
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: main
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取仓库基础文件
        uses: actions/checkout@main

      - name: 安装Ubuntu22编译全部依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libncurses5-dev unzip gawk git gettext libz-dev flex bison libusb-dev ruby python3-distutils

      - name: 拉取OpenWrt最新源码
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

      - name: 更新安装软件源
        run: |
          cd $OPENWRT_PATH
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 开启网页远程SSH，任务暂停等待你登录配置
      - name: 开启远程SSH，手动配置menuconfig
        uses: mxschmitt/action-tmate@v3

      - name: 配置固化
        run: |
          cd $OPENWRT_PATH
          make defconfig

      - name: 预下载源码包
        run: |
          cd $OPENWRT_PATH
          make download -j$(nproc)

      - name: 开始编译固件
        id: compile
        run: |
          cd $OPENWRT_PATH
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 固件、插件上传Release
        if: steps.compile.outputs.status == 'success'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: OpenWrt‑Main‑${{ github.sha }}
          release_name: 手动SSH配置编译成品
          files: |
            ${{ env.OPENWRT_PATH }}/bin/targets/*/*/*.img
            ${{ env.OPENWRT_PATH }}/bin/targets/*/*/*.tar.gz
            ${{ env.OPENWRT_PATH }}/bin/packages/*/*/*.ipk
          draft: false
          prerelease: false
